### ISSUE TITLE
organize your `src` folder.

### ISSUE THREAD

**Issue by kernelism** [akash-r-prabhu/spotify-clone#1]
Put CSS files in a separate folder and modularize your code into pages and components. React is easier to debug that way. It's readable too. Check this out -> [styled-components](https://styled-components.com/docs/basics#motivation)

**Comment by akash-r-prabhu** [comment]
> Put CSS files in a separate folder and modularize your code into pages and components. React is easier to debug that way. It's readable too. Check this out -> [styled-components](https://styled-components.com/docs/basics#motivation)

Sure thanks 👍
